version: '3.8'

services:
  # 기존 인프라 (Redis, PostgreSQL, Kafka)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - nestjs-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: nestjs_cqrs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nestjs-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - nestjs-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - nestjs-network

  # NestJS 애플리케이션 노드들
  nestjs-node-1:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ID=node-1
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
      - DATABASE_NAME=nestjs_cqrs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - nestjs-network
    volumes:
      - ./logs:/app/logs

  nestjs-node-2:
    build: .
    ports:
      - "3001:3000"
    environment:
      - PORT=3000
      - NODE_ID=node-2
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
      - DATABASE_NAME=nestjs_cqrs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - nestjs-network
    volumes:
      - ./logs:/app/logs

  nestjs-node-3:
    build: .
    ports:
      - "3002:3000"
    environment:
      - PORT=3000
      - NODE_ID=node-3
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres123
      - DATABASE_NAME=nestjs_cqrs
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    networks:
      - nestjs-network
    volumes:
      - ./logs:/app/logs

  # 로드 밸런서 (선택사항)
  nginx:
    image: nginx:alpine
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs-node-1
      - nestjs-node-2
      - nestjs-node-3
    networks:
      - nestjs-network

volumes:
  postgres_data:

networks:
  nestjs-network:
    driver: bridge 