apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nestjs-cqrs-saga
  labels:
    app: postgres
    component: database
type: Opaque
data:
  # postgres123 (base64 encoded)
  POSTGRES_PASSWORD: cG9zdGdyZXMxMjM=
  # postgres (base64 encoded) 
  POSTGRES_USER: cG9zdGdyZXM=
  # nestjs_cqrs (base64 encoded)
  POSTGRES_DB: bmVzdGpzX2NxcnM= 